### ISSUE TITLE
Space in the string for the cmd line args is creating an error

### ISSUE THREAD

**Issue by johnmathe1** [ONDC-Official/reference-implementations#7]
Here is part of my verify_authorisation_header --> 'Signature keyId="buyer-app.ondc.org|207|ed25519",
The space between Signature and keyId is the issue that creates the index out of range

> Traceback (most recent call last):
  File "C:\Users\johnm\source\repos\ondc\reference-implementations\utilities\signing_and_verification\cryptic_utils.py", line 107, in <module>
    fire.Fire()
  File "C:\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\johnm\source\repos\ondc\reference-implementations\utilities\signing_and_verification\cryptic_utils.py", line 88, in verify_authorisation_header
    header_parts = get_filter_dictionary_or_operation(auth_header.replace("Signature ", ""))
  File "C:\Users\johnm\source\repos\ondc\reference-implementations\utilities\signing_and_verification\cryptic_utils.py", line 62, in get_filter_dictionary_or_operation
    value = splits[1].strip()
IndexError: list index out of range

**Comment by kj2222** [comment]
Is there any fix for this?
